
[build]
  command = "echo 'No build needed'"
  publish = "."

[build.environment]
  USER_ID = "43b4me_OTEicELK5"  # Remplacez par votre vrai User ID
  SERVICE_ID = "service_qg02cut"  # Remplacez par votre Service ID
  TEMPLATE_ID = "template_125rlc5"  # Remplacez par votre Template ID
  NODE_ENV = "production"

[context.production.environment]
  USER_ID = "43b4me_OTEicELK5"
  SERVICE_ID = "service_qg02cut"
  TEMPLATE_ID = "template_125rlc5"
  NODE_ENV = "production"
  SECURE_ORIGIN = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self' https://api.emailjs.com; frame-ancestors 'none'; form-action 'self';"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=()"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Host = "btece-formation.netlify.app"}  # Votre domaine réel

[[redirects]]
  from = "/.env"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/wp-admin/*"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/.well-known/*"
  to = "/404.html"
  status = 404
  force = true

# Protection contre les attaques courantes
[[headers]]
  for = "/*.php"
  [headers.values]
    Content-Type = "text/plain"