
[build]
  publish = "."
  command = "npm install && npm run build"

[build.environment]
  NODE_ENV = "production"
  # Désactiver le scan standard des secrets
  SECRETS_SCAN_ENABLED = "false"
  # Désactiver le scan intelligent (smart detection)
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[context.production.environment]
  NODE_ENV = "production"
  SECURE_ORIGIN = "true"

# Configuration de sécurité avancée
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; img-src 'self' data: https:; font-src 'self' https://cdnjs.cloudflare.com; connect-src 'self' https://api.emailjs.com https://*.netlify.app; frame-ancestors 'none'; form-action 'self' https://*.netlify.app"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

# Headers pour les fonctions Netlify (formulaires)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Optimisation du cache
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Protection des fichiers sensibles
[[headers]]
  for = "/*.env"
  [headers.values]
    Content-Type = "text/plain"

# Redirections SPA - EXCLURE le traitement des formulaires
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Path = ["!/.netlify/functions/*", "!/assets/*"]}

# Traitement des formulaires Netlify
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Protection contre les scans
[[redirects]]
  from = "/.env"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/wp-admin/*"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/.well-known/*"
  to = "/404.html"
  status = 404
  force = true

# Redirection HTTPS canonique
[[redirects]]
  from = "http://btece-formation.netlify.app/*"
  to = "https://btece-formation.netlify.app/:splat"
  status = 301
  force = true