

[build]
  command = "echo 'No build needed'"
  publish = "."  # Ou "src" si votre HTML est dans un dossier src

[context.production.environment]
  NODE_ENV = "production"
  # Sécurité HTTP
  SECURE_ORIGIN = "true"
  REFERRER_POLICY = "strict-origin-when-cross-origin"
  PERMISSIONS_POLICY = "geolocation=(), microphone=()"
  X_FRAME_OPTIONS = "DENY"
  X_CONTENT_TYPE_OPTIONS = "nosniff"
  X_XSS_PROTECTION = "1; mode=block"

[[headers]]
  for = "/*"
  [headers.values]
    # Headers de sécurité
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-ancestors 'none'; form-action 'self';"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=()"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  # Protection contre l'open redirect
  conditions = {Host = "btece-formation.com"}  # Remplacez par votre vrai domaine

[[redirects]]
  from = "/.env"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/wp-admin/*"
  to = "/404.html"
  status = 404
  force = true