
[build]
  publish = "."
  command = "npm install && npm run build"

[build.environment]
  NODE_ENV = "production"

[context.production.environment]
  NODE_ENV = "production"
  SECURE_ORIGIN = "true"

# Configuration de sécurité avancée
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; img-src 'self' data: https:; font-src 'self' https://cdnjs.cloudflare.com; connect-src 'self' https://api.emailjs.com; frame-ancestors 'none'; form-action 'self'"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

# Optimisation du cache
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Protection des fichiers sensibles
[[headers]]
  for = "/*.env"
  [headers.values]
    Content-Type = "text/plain"

# Redirections SPA - EXCLURE le traitement des formulaires
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

# Exclure le endpoint de soumission de formulaire de la redirection SPA
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = false

# Protection contre les scans
[[redirects]]
  from = "/.env"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/wp-admin/*"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/.well-known/*"
  to = "/404.html"
  status = 404
  force = true

# Redirection HTTPS canonique
[[redirects]]
  from = "http://btece-formation.netlify.app/*"
  to = "https://btece-formation.netlify.app/:splat"
  status = 301
  force = true

# Configuration spécifique pour le traitement des formulaires Netlify
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# Désactiver la redirection SPA pour les soumissions de formulaire
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  conditions = {Path = ["/"]}
  force = false